pipeline {
    agent any

    tools {
        jdk 'Java21'
        maven 'Maven'
    }

    stages {

        stage('Parallel Build') {
            parallel {

                stage('Build Maven') {
                    steps {
                        dir('vehicle-parking') {
                            sh 'mvn clean package'
                        }
                    }
                }

                stage('Build CMake') {
                    steps {
                        dir('cmake-project') {
                            sh '''
                                mkdir -p build
                                cd build
                                cmake ..
                                make
                            '''
                        }
                    }
                }

            }
        }

    }

    post {
        success {
            echo 'Both Maven and CMake projects built successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
